from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support import expected_conditions as EC


# ошибка с неккоректным паролем
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Зарегистрироваться")))
registration = (driver.find_element(By.LINK_TEXT, "Зарегистрироваться"))
registration.click()
name = (driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input"))
name.send_keys("Анастасия")
email = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
email.send_keys("polov1234567891011@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[3]//input")
password.send_keys("12345")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
entrance = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
entrance.click()
name.clear()
email.clear()
password.clear()
name.send_keys("Анастасия")
email.send_keys("polov1234567891011@yandex.ru")
password.send_keys("123456")
entrance.click()
driver.quit()

# успешная регистрация
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Зарегистрироваться")))
registration = (driver.find_element(By.LINK_TEXT, "Зарегистрироваться"))
registration.click()
driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input").send_keys("Анастасия")
driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input").send_keys("polov12345678910@yandex.ru")
driver.find_element(By.XPATH, ".//body//form//fieldset[3]//input").send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
entrance = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
entrance.click()
driver.quit()

# вход по кнопке «Войти в аккаунт» на главной
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
entrances = driver.find_element(By.XPATH, ".//body//main//section[2]//button")
entrances.click()
email = driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input")
email.send_keys("polov12345@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
password.send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
authorization = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
authorization.click()
driver.quit()

# вход через кнопку «Личный кабинет»
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
email = driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input")
email.send_keys("polov12345@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
password.send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
authorization = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
authorization.click()
driver.quit()

# вход через кнопку в форме регистрации
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Зарегистрироваться")))
registration = (driver.find_element(By.LINK_TEXT, "Зарегистрироваться"))
registration.click()
entrance = (driver.find_element(By.CLASS_NAME, "Auth_link__1fOlj"))
entrance.click()
email = driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input")
email.send_keys("polov12345@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
password.send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
authorization = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
authorization.click()
driver.quit()

# вход через кнопку в форме восстановления пароля
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
restore = (driver.find_element(By.LINK_TEXT, "Восстановить пароль"))
restore.click()
entrance = (driver.find_element(By.CLASS_NAME, "Auth_link__1fOlj"))
entrance.click()
email = driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input")
email.send_keys("polov12345@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
password.send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
authorization = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
authorization.click()
driver.quit()

# переход в личный кабинет
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
driver.quit()

# переход из личного кабинета в конструктор
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.LINK_TEXT, "Личный Кабинет")
cabinet.click()
designer = driver.find_element(By.LINK_TEXT, "Конструктор")
designer.click()
cabinet.click()
logo = driver.find_element(By.CLASS_NAME, "AppHeader_header__logo__2D0X2")
logo.click()
driver.quit()

# переходы к разделам:«Булки»,«Соусы»,«Начинки»
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
sauces = driver.find_element(By.XPATH, ".//body//main//section[1]//div[1]")
fillings = driver.find_element(By.XPATH, ".//body//main//section[1]//div[3]")
sauces.click()
fillings.click()
driver.quit()

# выход из аккаунта
driver = webdriver.Firefox()
driver.maximize_window()
driver.get('https://stellarburgers.nomoreparties.site/')
cabinet = driver.find_element(By.XPATH, ".//body//header//nav/a")
cabinet.click()
email = driver.find_element(By.XPATH, ".//body//form//fieldset[1]//input")
email.send_keys("polov12345@yandex.ru")
password = driver.find_element(By.XPATH, ".//body//form//fieldset[2]//input")
password.send_keys("123456")
WebDriverWait(driver, 3).until(expected_conditions.element_to_be_clickable((By.CLASS_NAME, "button_button__33qZ0")))
authorization = (driver.find_element(By.CLASS_NAME, "button_button__33qZ0"))
authorization.click()
WebDriverWait(driver, 20).until(expected_conditions.element_to_be_clickable((By.XPATH, ".//body//header//nav/a")))
WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, ".//body//header//nav/a")))
cabinet_authorization = (driver.find_element(By.LINK_TEXT, "Личный Кабинет"))
driver.execute_script("arguments[0].click();", cabinet_authorization)
WebDriverWait(driver, 50).until(EC.presence_of_element_located((By.CSS_SELECTOR, '.Account_button__14Yp3'))).click()
driver.quit()